### ISSUE TITLE
Graph Application Graphql Architect failed to install

### ISSUE THREAD

**Issue by alamfsmb** [grand-stack/graphql-architect#5] opened 2020-07-31 15:04 UTC
I tried to install GraphQL Architect by pasting `https://registry.npmjs.org/@grandstack/graphql-architect` in the Graph Apps Install field, but an error pops up with "Graph Application Graphql Architect failed to install" 

When I look at the log.log for my Neo4j Desktop, it says 
`[2020-07-31 09:38:01.874] [warn] ERROR: {"error":"404 - Not found","url":"https://registry.npmjs.org/@grandstack/graphql-architect"} 
[2020-07-31 09:38:01.875] [error] Graph app installation failed undefined`

Not sure what's going on since the URL seems correct and I can install various other graph apps. 

Using Neo4j Desktop 1.3.3 @ Windows_NT 10.0.17763

**Comment by Tyguy160** [comment] 2020-08-03 13:39
I'm having the same issue on the same application version and Windows version. @johnymontana Any ideas on what we can do to resolve this?

**Comment by Tyguy160** [comment] 2020-08-03 19:18
@alamfsmb I found a workout. Download the latest tarball listed within the registry (v.0.0.26 as of this writing) and then drag it into the area of the Desktop app where you previously copied in the URL above.

Tarball URL: https://registry.npmjs.org/@grandstack/graphql-architect/-/graphql-architect-0.0.26.tgz

**Comment by alamfsmb** [comment] 2020-08-03 19:33
@Tyguy160 Awesome, I got it installed. Thanks so much for finding the tarball and sharing the workaround!

**Comment by johnymontana** [comment] 2020-08-04 15:22
Thanks for reporting @alamfsmb and thanks for posting the workaround @Tyguy160! This is caused by a bug in Neo4j Desktop related to how it interacts with npm when installing graph apps. Currently, it is impacting the installation of any graph app hosted on npm (not just GraphQL Architect). The PR fix is in and will be included in the next release of Neo4j Desktop which should be soon.

In the meantime installing via the .tgz that @Tyguy160 linked above will work, just be aware that installing via that method will not pick up the automatic updates for GraphQL Architect going forward. So if you install via the .tgz method, I would check back and install using the Graph Apps Gallery once this issue is fixed.

**Comment by johnymontana** [comment] 2020-08-04 16:51
OK this is now fixed in the latest release of Neo4j Desktop. If you upgrade to Neo4j Desktop v1.3.4 then you should be able to install GraphQL Architect via the Graph Apps Gallery or by pasting in `https://registry.npmjs.org/@grandstack/graphql-architect` in the install form field

**Closed as completed by johnymontana** 2020-08-04 16:51 UTC
